#!/bin/sh

printf "====================CWOMPILER (tm) 🐈================\n\n"

printf "FULL:: \n"
CODE=$(cat code.lol)
node -e "parser = require('lolcode'); parser(\`$CODE\`); process.exit()" >> a.out

printf "APPENDING TESTS:: \n"
cat tests >> a.out

printf "RESULTING FILE:: \n"
cat a.out

printf "RUNNING TESTS:: \n"
#node a.out

